// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR62DkYqENjAYvi0ENyQTaf8EHd4S2Qtw',
    appId: '1:375495246145:web:74aff7f21d132d9a1b21c0',
    messagingSenderId: '375495246145',
    projectId: 'madar-d56bb',
    authDomain: 'madar-d56bb.firebaseapp.com',
    storageBucket: 'madar-d56bb.firebasestorage.app',
    measurementId: 'G-4429F92CM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsNcon1_GcqQ6O_dOHpwIFg2KxsfcO0PM',
    appId: '1:375495246145:android:1329c3b3cefe05361b21c0',
    messagingSenderId: '375495246145',
    projectId: 'madar-d56bb',
    storageBucket: 'madar-d56bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpaa8aKOq70Y_xghQH2jcp7HeUWxLxKlg',
    appId: '1:375495246145:ios:46e4fe1d73c394731b21c0',
    messagingSenderId: '375495246145',
    projectId: 'madar-d56bb',
    storageBucket: 'madar-d56bb.firebasestorage.app',
    iosBundleId: 'com.example.madar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpaa8aKOq70Y_xghQH2jcp7HeUWxLxKlg',
    appId: '1:375495246145:ios:46e4fe1d73c394731b21c0',
    messagingSenderId: '375495246145',
    projectId: 'madar-d56bb',
    storageBucket: 'madar-d56bb.firebasestorage.app',
    iosBundleId: 'com.example.madar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR62DkYqENjAYvi0ENyQTaf8EHd4S2Qtw',
    appId: '1:375495246145:web:874ebb694fa0cfc01b21c0',
    messagingSenderId: '375495246145',
    projectId: 'madar-d56bb',
    authDomain: 'madar-d56bb.firebaseapp.com',
    storageBucket: 'madar-d56bb.firebasestorage.app',
    measurementId: 'G-R5MFH5G2CB',
  );
}
